from enum import Flag, auto

class Category(Flag):
    """Categories."""
    PHILOSOPHY = auto()
    PHYSICS = auto()
    MATHEMATICS = auto()
    COMPUTER_SCIENCE = auto()
    INFORMATION_TECHNOLOGY = auto()
    CHEMISTRY = auto()
    BIOLOGY = auto()
    ECONOMICS = auto()
    ENGINEERING = auto()
    GEOSCIENCES = auto()
    AGRICULTURE = auto()
    SOCIAL_SCIENCES = auto()
    BUSINESS = auto()
    HEALTH_SCIENCES = auto()
    EDUCATION = auto()
    ARTS = auto()
    MEDIA = auto()
    COMMUNICATION = auto()
    HISTORY = auto()
    LITERATURE = auto()
    LAW = auto()
    POLITICAL_SCIENCE = auto()
    RELIGION = auto()
    PSYCHOLOGY = auto()
    LANGUAGE = auto()
    ASTRONOMY = auto()

class Subcategory(Flag):
    """Subcategories."""

    # Philosophy
    ONTOLOGY = auto()
    METAPHYSICS = auto()
    GNOSIOLOGY = auto()
    EPISTEMOLOGY = auto()
    LOGIC = auto()
    ETHICS = auto()
    PHILOSOPHICAL_THEORY = auto()
    AESTHETICS = auto()

    # Physics
    ATOMIC_PHYSICS = auto()
    MOLECULAR_PHYSICS = auto()
    NUCLEAR_PHYSICS = auto()
    PARTICLE_PHYSICS = auto()
    QUANTUM_PHYSICS = auto()
    CLASSICAL_MECHANICS = auto()
    STRING_THEORY = auto()
    THERMODYNAMICS = auto()
    OPTICS = auto()
    ACOUSTICS = auto()
    RELATIVITY = auto()

    # Mathematics
    ALGEBRA = auto()
    CALCULUS = auto()
    GEOMETRY = auto()
    ANALYTIC_GEOMETRY = auto()
    ANALYTIC_NUMBER_THEORY = auto()
    ANALYTIC_SET_THEORY = auto()
    COMBINATORICS = auto()
    DIFFERENTIAL_GEOMETRY = auto()
    DIFFERENTIAL_EQUATIONS = auto()
    FUNCTIONAL_ANALYSIS = auto()
    GROUP_THEORY = auto()
    LINEAR_ALGEBRA = auto()
    STATISTICS = auto()
    PROBABILITY = auto()
    TOPOLOGY = auto()

    # Computer Science
    ARTIFICIAL_INTELLIGENCE = auto()
    MACHINE_LEARNING = auto()
    DATA_SCIENCE = auto()
    SOFTWARE_ENGINEERING = auto()
    COMPUTER_NETWORKS = auto()
    DATABASES = auto()
    CYBERSECURITY = auto()
    OPERATING_SYSTEMS = auto()
    AI = auto()

    # Biology
    GENETICS = auto()
    MICROBIOLOGY = auto()
    ECOLOGY = auto()
    MOLECULAR_BIOLOGY = auto()
    ZOOLOGY = auto()
    BOTANY = auto()
    ANATOMY = auto()
    PHYSIOLOGY = auto()
    EVOLUTIONARY_BIOLOGY = auto()

    # Engineering
    ELECTRICAL = auto()
    MECHANICAL = auto()
    CIVIL = auto()
    AEROSPACE = auto()
    ENVIRONMENTAL = auto()
    BIOMEDICAL = auto()
    SOFTWARE = auto()
    CHEMICAL = auto()
    ROBOTICS = auto()
    INDUSTRIAL = auto()

    # Social Sciences
    SOCIOLOGY = auto()
    ANTHROPOLOGY = auto()
    POLITICAL_THEORY = auto()
    CRIMINOLOGY = auto()
    HUMAN_GEOGRAPHY = auto()

    # History
    CONTEMPORARY = auto()
    ANCIENTY = auto()
    MEDIEVAL = auto()
    MODERN = auto()
    MILITARY = auto()
    ART = auto()

    # Literature
    POETRY = auto()
    FICTION = auto()
    DRAMA = auto()
    PROSE = auto()
    LITERARY_THEORY = auto()
    COMPARATIVE_LITERATURE = auto()

    # Law
    CIVIL_LAW = auto()
    CRIMINAL_LAW = auto()
    CONSTITUTIONAL_LAW = auto()
    INTERNATIONAL_LAW = auto()
    CORPORATE_LAW = auto()

    # Religion
    THEOLOGY = auto()
    COMPARATIVE_RELIGION = auto()
    RELIGIOUS_PHILOSOPHY = auto()
    ETHICAL_THEOLOGY = auto()

    # Psychology
    COGNITIVE_PSYCHOLOGY = auto()
    CLINICAL_PSYCHOLOGY = auto()
    DEVELOPMENTAL_PSYCHOLOGY = auto()
    BEHAVIORAL_PSYCHOLOGY = auto()
    PSYCHOANALYSIS = auto()

    # Language
    LINGUISTICS = auto()
    SEMANTICS = auto()
    SYNTAX = auto()
    PHONOLOGY = auto()
    PRAGMATICS = auto()
    GRAMMAR = auto()
    HISTORICAL_LINGUISTICS = auto()

    #Arts
    MUSIC = auto()
    VISUAL = auto()
    PAINTING = auto()
    SCULPTURE = auto()
    PHOTOGRAPHY = auto()
    DRAWING = auto()
    ARCHITECTURE = auto()
    DESIGN = auto()
    GRAPHIC_DESIGN = auto()
    INDUSTRIAL_DESIGN = auto()
    INTERIOR_DESIGN = auto()
    CERAMICS = auto()
    CRAFTS = auto()
    FILM = auto()
    THEATER = auto()
    DANCE = auto()
    OPERA = auto()
    LITERARY = auto()
    CALLIGRAPHY = auto()
    FASHION = auto()
    DIGITAL = auto()
    PERFORMANCE = auto()
    INSTALLATION = auto()
    STREET = auto()
